version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: go get -d ./...
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
          context: SonarCloud
